# Generated by Django 5.1.3 on 2024-11-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_productimage_file_productimage_feedback_and_more'),
        ('users', '0006_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='products.product'),
        ),
    ]
